elastic_drives:
  drive_x:
    damping_ratio: 0.49
    stiffness: 5977.08
  drive_y:
    damping_ratio: 0.68
    stiffness: 7162.08
  drive_z:
    damping_ratio: 1.20
    stiffness: 3861.11
  payload: 3.0
simulation:
  ref_mode: 2 # 0: stand_still, 1: sinusoidal, 2: PTP sequence
  seed: -1 # -1 for random seed, otherwise specify an integer
  sim_time: 10.0
  time_step: 0.01
  cut_off_time: 2.0
